id: P57444551
initial_creation_type: input
source_metadata:
  title: Biographies
  parent: 3. Various collections
  source: https://sakyalibrary.com
  bases:
    a838:
      title: དམར་ཆོས་ཀྱི་རྒྱལ་པོས་ས་པཎ་གྱི་གསུང་སྒྲོས་བྲིས་པ་ལམ་འབྲས་བོད་ཀྱི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཞིབ་མོ་རྡོ་རྗེ།
      author: དམར་ཆོས་ཀྱི་རྒྱལ་པོ།
      base_file: a838.txt
      order: 1
    626a:
      title: རྣལ་འབྱོར་དབང་ཕྱུག་གི་ལོ་རྒྱུས་ཟུར་ཙམ་བརྗོད་པ།
      author: འཕགས་པའི་སློབ་མ་ཆ་རྒན།
      base_file: 626a.txt
      order: 2
    60a0:
      title: ཆོས་རྗེ་བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་ཐོག་མཐའ་བར་གསུམ་དུ་དགེ་བ།
      author: ལོ་ཙཱ་བ་གྲགས་པ་རྩེ་མོ།
      base_file: 60a0.txt
      order: 3
    de80:
      title: ཐེག་ཆེན་ཆོས་རྗེ་ཀུན་དགའ་བཀྲ་ཤིས་ཀྱི་རྣམ་ཐར་ངོ་མཚར་རྒྱ་མཚོའི་གཏེར།
      author: ཀུན་དགའ་རྒྱལ་མཚན།
      base_file: de80.txt
      order: 4
    b2e4:
      title: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས་ཀྱི་རྣམ་ཐར།
      author: རཏྣ་སཾ་བྷ་ཝ།
      base_file: b2e4.txt
      order: 5
    ee16:
      title: རེད་མདའ་བ་ཆེན་པོ་གཞོན་ནུ་བློ་གྲོས་ཀྱི་རྣམ་ཐར་ངོ་མཚར་རྨད་བྱུང་།
      author: མངའ་རིས་པ་སངས་རྒྱས་རྩེ་མོ།
      base_file: ee16.txt
      order: 6
    1cfd:
      title: རོང་སྟོན་ཆེན་པོའི་རྣམ་ཐར་ཕྲིན་ལས་རྒྱུན་མི་ཆད་པའི་རྟེན་འབྲེལ་བཟང་པོ་ཞེས་བྱ་བ།
      author: ནམ་མཁའ་དཔལ་བཟང་།
      base_file: 1cfd.txt
      order: 7
    9b7c:
      title: བྱམས་ཆེན་རབ་འབྱམས་པ་ཀུན་མཁྱེན་ཆོས་ཀྱི་རྒྱལ་པོ་སངས་རྒྱས་འཕེལ་གྱི་རྣམ་ཐར་དད་གུས་ཆུ་འཛིན་རྣམ་པར་རོལ་པ།
      author: འཇམ་དབྱངས་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: 9b7c.txt
      order: 8
    1f5e:
      title: གློ་བོ་མཁན་ཆེན་བསོད་ནམས་ལྷུན་གྲུབ་ཀྱི་རྟོགས་བརྗོད་དཔལ་ལྡན་བླ་མ་འཇམ་པའི་དབྱངས་ཀྱི་རྣམ་ཐར་ལེགས་བཤད་གསུམ་ལྡན།
      author: གྲོལ་མཆོག
      base_file: 1f5e.txt
      order: 9
    3a44:
      title: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་བྱམས་པ་ཀུན་དགའ་བསྟན་པའི་ཉི་མ།
      base_file: 3a44.txt
      order: 10
    575c:
      title: བདེ་མཆོག་ལཱུ་ཧི་པའི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
      author: ཤར་པ་ཆེན་པོ་རྡོ་རྗེ་འོད་ཟེར།
      base_file: 575c.txt
      order: 11
    075a:
      title: སྐྱེས་མཆོག་རིན་ཆེན་བཟང་པོའི་རྣམ་ཐར་ངོ་མཚར་བ།
      author: སྒྲོལ་མ་ཁའི་དང་། ཛྙཱ་ན་ཤྲཱི།
      base_file: 075a.txt
      order: 12
    b081:
      title: རྗེ་བཙུན་རིན་པོ་ཆེ་བསོད་ནམས་རྩེ་མོའི་རྣམ་པར་ཐར་པ་དོན་གྱི་སྙིང་པོ་བསྡུས་པ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: b081.txt
      order: 13
    877d:
      title: རེད་མདའ་བའི་རྣམ་ཐར་ངོ་མཚར་རྨད་བྱུང་།
      author: མངའ་རིས་པ་སངས་རྒྱས་རྩེ་མོ།
      base_file: 877d.txt
      order: 14
    75c2:
      title: ཆོས་རྗེ་རྫོང་པ་ཀུན་དགའ་རྒྱལ་མཚན་པའི་རྣམ་ཐར།
      author: དཔལ་ལྡན་ཆོས་སྐྱོང་།
      base_file: 75c2.txt
      order: 15
    9bc3:
      title: ཀུན་མཁྱེན་དྭགས་པོ་བ་བཀྲ་ཤིས་རྣམ་རྒྱལ་གྱི་རྣམ་པར་ཐར་པ་ངོ་མཚར་གྱི་རྒྱ་མཚོ།
      author: དྭགས་པོའི་པཎྜི་ཏ་ཀརྨ་ཕྲིན་ལས།
      base_file: 9bc3.txt
      order: 16
    445a:
      title: རྗེ་བཙུན་ཞྭ་ལུ་ལོ་ཙཱ་བའི་རྣམ་པར་ཐར་པ་བརྗེད་བྱང་ནོར་བུའི་ཁྲི་ཤིང་། དཔལ་རིན་ཆེན་བཀྲ་ཤིས་ཀྱིས་མཛད་པ།
      author: དཔལ་རིན་ཆེན་བཀྲ་ཤིས།
      base_file: 445a.txt
      order: 17
    ce69:
      title: དཔལ་ས་སྐྱ་ལོ་ཙཱ་བ་ཆེན་པོའི་རྣམ་པར་ཐར་པ་འཇམ་དཔའི་དབྱངས་ཀྱི་ཡོན་ཏན་རྣམ་པར་བཀོད་པ།
      author: ཤཱཀྱའི་དགེ་སློང་དཀོན་མཆོག་ལྷུན་འགྲུབ།
      base_file: ce69.txt
      order: 18
    a618:
      title: དཔལ་ལྡན་བླ་མ་དཀོན་མཆོག་བཟང་པོའི་རྣམ་པར་ཐར་པ་དད་པའི་ལྗོན་ཤིང་རྒྱས་བྱེད།
      author: བློ་གྲོས་རྒྱ་མཚོ།
      base_file: a618.txt
      order: 19
    c1a2:
      title: ཁ་ཆེ་པཎ་ཆེན་གྱི་རྣམ་ཐར་རིན་པོ་ཆེའི་ཕྲེང་བ། ཁྲོ་ཕུ་ལོ་ཙཱ་བ་བྱམས་པའི་དཔལ་གྱིས་མཛད་པ་གཞིས་བཅས་པ།
      author: ཁྲོ་ཕུ་ལོ་ཙཱ་བ་བྱམས་པའི་དཔལ།
      base_file: c1a2.txt
      order: 20
    f0d9:
      title: པན་གྲུབ་གསུམ་གྱི་རྣམ་ཐར་དཔག་བསམ་འཁྲི་ཤིང་།
      author: ''
      base_file: f0d9.txt
      order: 21
    c0e1:
      title: མཁས་གྲུབ་ཁྱུང་པོ་རྣལ་འབྱོར་པའི་རྣམ་ཐར།
      author: ''
      base_file: c0e1.txt
      order: 22
    478e:
      title: བླ་མ་སྐྱེར་སྒང་པའི་རྣམ་ཐར་དང་། གསང་རྣམ་གཉིས།
      author: ''
      base_file: 478e.txt
      order: 23
    34dc:
      title: དཔལ་ལྡན་བླ་མ་རྨོག་ཅོག་པ་ཆེན་པོའི་རྣམ་པར་ཐར་པ།།
      author: ''
      base_file: 34dc.txt
      order: 24
created_at: '2022-04-06T17:40:24.861481'
last_modified_at: '2022-04-06T17:40:24.861511'
